apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-script
data:
  "auth.py": |
    #!/usr/bin/env python3
    import sys

    print("{'" + sys.argv[1] + "': {  }}")
    print(sys.argv[2])
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config: |
    inside-cluster: true
    restler-img: "{{ $.Values.controller.restlerImage.repository }}:{{ $.Values.controller.restlerImage.tag }}"
    username: "{{ $.Values.controller.restlerConfig.userName }}"
    secret: "{{ $.Values.controller.restlerConfig.secret }}"
    {{- if $.Values.controller.restlerConfig.onlyMarked }}
    only-marked: true
    {{- end }}
    home-ns: "{{ $.Release.Namespace }}"
    job-img: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
    restler-time-budget: "{{ $.Values.controller.restlerConfig.timeBudget }}"
